packages:
  - apps/*
  - packages/*
  - tooling/*

catalog:
  "@tanstack/react-query": ^5.66.5
  eslint: ^9.19.0
  prettier: ^3.4.2
  tailwindcss: ^3.4.14
  typescript: ^5.7.3
  zod: ^3.24.2
  dotenv-cli: ^8.0.0
  convex: ^1.19.3
  "convex-helpers": ^0.1.71
  date-fns: ^4.1.0
  postcss: ^8.5.1
  "@convex-dev/auth": ^0.0.80
  "@types/node": ^22.10.10

catalogs:
  react19:    
    react: ^19.0.0
    react-dom: ^19.0.0
    "@types/react": ^19
    "@types/react-dom": ^19
